### PR TITLE
Fix #315: Add MenuSelectionTask

### LINKED ISSUE #315: Example of Adding a Concept to the Model
It would be nice to provide an end-to-end example of how to add a new concept to the Coffee Editor's model, demonstrating how this trickles down to all aspects of the system, both back-end and front-end:

- coffee machine model definition
- tree/form editor
- textual editor
- diagram editor
- model validation
- workflow analysis

The intent is not to integrate this into the repository main-line, but rather to publish it as a branch that can be compared with its base commit to show all of the changes that implement the new model. It is expected that as capabilities are added over time to the Coffee Editor, this example may warrant changes to adopt them, but that is not in scope of this feature request.

For purposes of this example, let us propose the addition of a new workflow node for interactive user input: a `MenuSelection` node. This node run-time semantics would be something like:

- on entry to the `MenuSeleciton` node, the coffee machine presents message to the user prompting for input
- and the machine presents two or more options for the user to choose from
- the coffee machine flow waits for the user to make a selection
  - if so configured, the `MenuSelection` node times out after a specified interval if the user does not make a selection, in which case the flow branches to handle this condition
  - otherwise, flow continues by passing the user's selection as input to the next node

So, this node must be configurable in the editor to specify several attributes:

- the prompt message (required)
- the the menu options (2 or more required)
- the time-out interval, in seconds (optional)

The node supports two outgoing flows:

- one carrying the user's selection as input to the target node
- one in the event of time-out, which would let a designer make a flow to a machine reset or exit the flow, etc.

New model validation constraints would include:
- a `MenuSelection` node may only have a time-out flow outgoing if a time-out interval is specified
- a `MenuSelection` node must have exactly one time-out flow outgoing if a time-out interval is specified
- a `MenuSelection` node must have exactly one selection flow outgoing

Illustrative use cases for this new node type could include
- selection of brew strength: light, medium, dark
- selection of cup size: 6 oz, 8 oz, 10 oz, 12 oz
- time out makes an implicit selection: a default, or the selection made previously
- time out cancels the brew and resets the coffee machine

### PR DESCRIPTION
**Pull request by cdamus**
This example illustrates the developer use case discussed in Issue #315, what all is involved in the definition of a new concept in the Coffee Model and the ripple effects of integrating it into the editor.

The Diagram editor now can do this:

diagram-editor

and the tree editor this:

form-editor

### CODE REVIEW

**Comment by eneufeld** [comment]
This looks good to me. Nina if you approve it is ready to be merged.

**Review by ndoschek — COMMENTED** [review]
Thank you very much for this great example Christian! It gives an excellent guideline on how to extend the concepts of the coffee editor. :tada: 
I noticed one minor cosmetic flaw, namely the workflow analysis graphic is cut off due to the additional task step I assume (please see the attached screenshot). But it is also fine by me, if this will be fixed in a separate issue.

image

**Comment by cdamus** [comment]
Thanks @ndoschek for pointing out this workflow analysis issue. I see not only that the flow is truncated, but it seems that whatever renders this doesn't have sufficient knowledge of the `MenuSelectionTask`: it isn't listed in the legend with its own colour.

I confess that this workflow analysis UI wasn't on my radar at all. I shall have to look into it; I cannot consider this task complete until it has been dealt with.

**Comment by cdamus** [comment]
Hi @ndoschek. I've force-pushed a new commit that adds the following:

- mapping of the new Menu Selection Task in the workflow analyzer app so that it shows up properly in the chart as a type distinct from the Manual Task
- in testing that, I looked around for what else I forgot and I found the whole workflow code generation app (oops! 😨) So I updated that, too, to account for the new Menu Selection Task concept

I've created issue #356 for the problem of truncated breadcrumbs, which can occur in any coffee model that has a sufficient number of tasks in its workflow. My PR #357 proposes an expedient fix for that and if we can get some version of that fix merged to master, then I would like to rebase this PR again on top of that for the best overall results.

**Comment by ndoschek** [comment]
Thanks a lot @cdamus ! I merged #357 into master!

**Comment by cdamus** [comment]
> Thanks a lot @cdamus ! I merged #357 into master!

Thanks, @ndoschek!. I have force-pushed commit f3974cc537990c951863cee853ff042b38dda22c which is rebased onto that breadcrumb fix. So, now the changes in the workflow analysis chart and code generation should be ready for review.

**Comment by ndoschek** [comment]
Thanks again Christian! Looks really great to me! :+1:

**Pull request merged**
