### PR TITLE
Use common settings and checkstyle from emfcloud

### LINKED ISSUE #343: Configure settings for consistent code style on backend
Add settings to all backend projects to ensure consistent code style (e.g. header, code formatting).
Such settings are already used in the `emfcloud-modelserver` project, maybe the settings for the `coffee-editor` can be somewhat similar.

### LINKED ISSUE #421: Fix headers in files
Since the update some headers are out of date or completely missing.

### PR DESCRIPTION
**Pull request by eneufeld**
Update settings and checkstyle config for backend projects.
Also add missing headers.

Fix #343
Fix #421

### CODE REVIEW

**Review by ndoschek — COMMENTED** [review]
Thanks Eugen, looks good to me!
Regarding the checkstyle, it also works as expected, but there are > 80 checkstyle issues. I think we should fix them before merging this PR, wdyt?
Also, we could integrate checkstyle as quality gate to the Jenkins job (as we do for the [`emfcloud-modelserver`](https://github.com/eclipse-emfcloud/emfcloud-modelserver/blob/f306c72fe45274fb6dd7398cee345be715cf963f/Jenkinsfile#L45) for example)

**Comment by ndoschek** [comment]
Thanks Eugen, I rebased and fixed the checkstyle issues.

**Review by ndoschek — APPROVED** [review]
Thanks @eneufeld , I rebased and fixed the checkstyle issues.
If the fixes are fine by you as well, we could merge it I'd say

**Comment by eneufeld** [comment]
@ndoschek I cannot approve my own PR, so please go ahead and merge

**Comment by eneufeld** [comment]
Thank you for all the additional fixes!

**Pull request merged**
