### PR TITLE
Update to latest modelserver version

### LINKED ISSUE #324: Compilation errors on breaking API changes in the Model Server
The Model Server APIs have some new breaking changes that the Coffee Editor needs to adapt to:

- the `ModelServerLauncher` constructor now requires a `ModelServerModule` for Guice injection configuration
- the `ModelServerClient::subscribe` method has removed the `String` parameter for resource format

### PR DESCRIPTION
**Pull request by ndoschek**
- Update dependencies and adjust some bundle constraints

<Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>>

Fixes #324

### CODE REVIEW

**Comment by eneufeld** [comment]
@cdamus can you check whether this solves your issue?

**Review by eneufeld — DISMISSED** [review]

**Comment by cdamus** [comment]
Thanks, @ndoschek and @eneufeld, this does get things back up and running for me.

I had to add a lot of missing dependencies in the back-end launch configs, though ... lots of new package and bundle requirements in `WorkflowAnalyzerServer.launch` and `RunSocketServer-Headless.launch`.

**Comment by eneufeld** [comment]
@ndoschek @cdamus can you sync and add include the launch files to this commit?

**Comment by cdamus** [comment]
> @ndoschek @cdamus can you sync and include the launch files to this commit?

cf. ndoschek/coffee-editor#1

**Review by eneufeld — APPROVED** [review]

**Comment by eneufeld** [comment]
I took the freedom to squash this :see_no_evil: . Thank you for the fix!

**Pull request merged**
