### PR TITLE
Fix code generation, debugging and icons in docker image

### PR DESCRIPTION
**Pull request by sgraband**
Move settings to package.json
Add gdb to docker image
Ignore already downloaded plugins for docker build

### CODE REVIEW

**Review by ndoschek — COMMENTED** [review]
Thanks, looks good overall! Can we open a follow-up ticket for the tree-view comparison?

Regarding the docker image related files:
- Do we really need two Dockerfiles?
- There is a folder `dockerfiles` - this seems to be outdated (as it references the previously used `run.sh`) - Would be great if we could clean that up with this change.

Nice to have: would be nice to provide yarn scripts in the main `package.json` for building the docker image and running it.

**Review by eneufeld — DISMISSED** [review]
Tested and works as expected

**Comment by sgraband** [comment]
Added a commit that:
- Only keeps tje k8s.dockerfile -> renames it to Dockerfile
- Removes the outdated dockerfiles folder
- Adds a yarn script for building the docker image

And added a follow up for the tree-view comparison: #489

**Review by eneufeld — APPROVED** [review]
Thank you!

**Pull request merged**
